### ISSUE TITLE
Error when attempting to sort by Entity

### ISSUE THREAD

**Issue by daryllabar** [Innofactor/PluginRegistration#56]
When attempting to view by entity (ctrl+Shift+e) I receive the following error:

Unhandled Exception: System.SystemException

The given key was not present in the dictionary.

   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Xrm.Sdk.PluginRegistration.MainControl.CreateCrmTreeNodes(CrmViewType view, Guid messageId, Guid messageEntityId, Boolean addToTree)
   at Xrm.Sdk.PluginRegistration.MainControl.LoadNodes(CrmViewType view)

**Comment by imranakram** [comment]
Duplicate of #60 #58. I haven't been able to reproduce this so far. Please checkout my comment on #60
