### ISSUE TITLE
Display by Entity/Message throws exception

### ISSUE THREAD

**Issue by mkalinov** [Innofactor/PluginRegistration#58]
Hi, an attempt to display by Entity or Message throws:

Unhandled Exception: System.SystemException

The given key was not present in the dictionary.

   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Xrm.Sdk.PluginRegistration.MainControl.CreateCrmTreeNodes(CrmViewType view, Guid messageId, Guid messageEntityId, Boolean addToTree)
   at Xrm.Sdk.PluginRegistration.MainControl.LoadNodes(CrmViewType view)

**Comment by Pillanagrovi** [comment]
Hi Mkalinov,
I am having the same issue with the tool, 
Have you found any solution for this error?

**Comment by mkalinov** [comment]
@Pillanagrovi 
Nope.
Issue exists in all version of PluginRegistration tool. I think it caused by metadata change yet reflected by tool developers, or, may be, Newtownsoft issue.

**Comment by AngelRodriguez8008** [comment]
I have the same Error. How can I help? Should I debug the Project? I have no experience with XrmToolBox Plugins development. But maybe some tests that can I run independently?

On Display by Message / Entity:

Unhandled Exception: System.SystemException

The given key was not present in the dictionary.

   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Xrm.Sdk.PluginRegistration.MainControl.CreateCrmTreeNodes(CrmViewType view, Guid messageId, Guid messageEntityId, Boolean addToTree)
   at Xrm.Sdk.PluginRegistration.MainControl.LoadNodes(CrmViewType view)

**Comment by imranakram** [comment]
This is fixed with #60
