### ISSUE TITLE
Error message when refreshing assemblies in a D365 Online organisation

### ISSUE THREAD

**Issue by markadamsnttdata** [Innofactor/PluginRegistration#65]
We have upgraded a couple of sandbox organisations to the latest set of D365 updates and now see an error message when refreshing the assembly list:

```
Unhandled Exception: System.SystemException

An item with the same key has already been added.

   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Xrm.Sdk.PluginRegistration.Controls.CrmTreeControl.AddNodes(TreeNodeCollection parentNodeList, List`1 nodes, Boolean checkNodes)
   at Xrm.Sdk.PluginRegistration.Controls.CrmTreeControl.AddNodes(TreeNodeCollection parentNodeList, List`1 nodes, Boolean checkNodes)
   at Xrm.Sdk.PluginRegistration.Controls.CrmTreeControl.AddNodes(TreeNodeCollection parentNodeList, List`1 nodes, Boolean checkNodes)
   at Xrm.Sdk.PluginRegistration.Controls.CrmTreeControl.LoadNodes(List`1 rootNodes)
   at Xrm.Sdk.PluginRegistration.MainControl.LoadNodes(CrmViewType view)
```
We don't see this error on the production organisation (not yet upgraded) or if we use the SDK registration tool so this may just be cosmetic ? One of the plugins we would expect to see is not appearing in the list.
---
- Deployment: Online
- DB Version: 9.1.0.15941
- XTB Version: 1.2020.2.37
- Tool Version: 3.2020.1.4

**Comment by markadamsnttdata** [comment]
Sorry - didn't see that someone has already raised this

**Comment by rappen** [comment]
Ref: #63
